# Generated by Django 5.0.2 on 2024-07-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Actice', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='customer', max_length=100),
        ),
    ]
