# Generated by Django 5.0.2 on 2024-07-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_rename_address_user_address_user_status_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
