# Generated by Django 5.0.2 on 2024-08-06 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='upload/products/')),
                ('tryon', models.FileField(upload_to='upload/tryon/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.category')),
            ],
        ),
    ]
