# Generated by Django 5.0.6 on 2024-08-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
