# Generated by Django 5.0.6 on 2024-08-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_rename_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default='NULL', upload_to='upload/profile'),
        ),
    ]
