# Generated by Django 5.0.1 on 2024-08-10 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.product')),
            ],
        ),
    ]
