# Generated by Django 5.0.1 on 2024-08-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0010_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer',
            new_name='Order',
        ),
    ]
