# Generated by Django 5.0.1 on 2024-08-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0011_rename_customer_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
    ]
