# Generated by Django 5.1 on 2024-08-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0013_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_men',
            field=models.BooleanField(default=False),
        ),
    ]
