# Generated by Django 5.1 on 2024-08-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0014_category_is_men'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_men',
        ),
    ]
