# Generated by Django 5.1 on 2024-08-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0016_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
