# Generated by Django 5.1 on 2024-08-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0018_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.TextField(max_length=100),
        ),
    ]
