# Generated by Django 5.1 on 2024-08-31 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0020_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
