# Generated by Django 5.1 on 2024-08-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0021_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flappy_bird_score',
            field=models.IntegerField(default=0),
        ),
    ]
