# Generated by Django 5.1 on 2024-08-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0023_alter_user_flappy_bird_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='flappy_bird_score',
            field=models.IntegerField(default=0),
        ),
    ]
