# Generated by Django 5.1 on 2024-09-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0024_alter_user_flappy_bird_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Client')], default='customer', max_length=100),
        ),
    ]
