# Generated by Django 5.1 on 2024-09-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0025_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='customer', max_length=100),
        ),
    ]
