# Generated by Django 5.1 on 2024-09-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0028_gamescore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='score',
            new_name='high_score',
        ),
        migrations.AddField(
            model_name='gamescore',
            name='last_score',
            field=models.IntegerField(default=0),
        ),
    ]
