# Generated by Django 5.1 on 2024-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0029_rename_score_gamescore_high_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='flappy_bird_score',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='customer', max_length=100),
        ),
        migrations.DeleteModel(
            name='GameScore',
        ),
    ]
