# Generated by Django 5.1 on 2024-09-03 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0030_remove_user_flappy_bird_score_alter_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='upload/user_profile')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientapp.user')),
            ],
        ),
    ]
