# Generated by Django 5.1 on 2024-09-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0032_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
