# Generated by Django 5.1 on 2024-09-03 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0033_user_game_score_gamescore_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game_score',
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='GameScore',
        ),
    ]
