# Generated by Django 5.1.1 on 2024-09-06 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0038_playerscore_delete_userscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerscore',
            name='player_name',
        ),
    ]
