# Generated by Django 5.1.1 on 2024-09-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0040_usercurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
