# Generated by Django 5.1.1 on 2024-09-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0041_coins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coins',
        ),
    ]
