# Generated by Django 5.1.1 on 2024-10-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0042_delete_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adjusted_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
