# Generated by Django 5.1.1 on 2024-10-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0043_order_adjusted_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adjusted_total',
        ),
    ]
