# Generated by Django 5.1.1 on 2024-10-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0044_remove_order_adjusted_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='credit_card', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=50),
        ),
    ]
