# Generated by Django 5.1.1 on 2024-10-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0045_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='COD', max_length=20),
        ),
    ]
